# Generated by Django 3.2.8 on 2021-11-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=1000)),
                ('Media', models.FileField(default='', upload_to='uploads/')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
    ]
