# Generated by Django 3.2.9 on 2021-12-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20211129_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='GMember',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='GAbout',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='GName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
