# Generated by Django 3.2.9 on 2021-12-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_person_userlevel'),
        ('group', '0005_remove_group_gmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Person_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmember',
            name='Group_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmember',
            name='Person_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
    ]
