# Generated by Django 3.2.9 on 2021-12-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20211201_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Person_fk',
        ),
    ]
