# Generated by Django 3.2.9 on 2021-12-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_remove_group_person_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTitle', models.CharField(blank=True, max_length=255)),
                ('GMessage', models.CharField(blank=True, max_length=255)),
                ('GPhoto', models.ImageField(upload_to='images/')),
                ('GVideo', models.FileField(null=True, upload_to='uploads/')),
                ('GGraph', models.FileField(upload_to='uploads/')),
                ('Group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'db_table': 'GroupSharing',
            },
        ),
    ]
