# Generated by Django 3.2.9 on 2021-12-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_person_userlevel'),
        ('sharing', '0001_initial'),
        ('group', '0008_groupsharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsharing',
            name='GGraph',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='GMessage',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='GPhoto',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='GTitle',
        ),
        migrations.RemoveField(
            model_name='groupsharing',
            name='GVideo',
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='Person_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='Sharing_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sharing.feed'),
            preserve_default=False,
        ),
    ]
