# Generated by Django 3.2.9 on 2021-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20211202_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsharing',
            name='Sharing_fk',
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='GGraph',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='GMessage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='GPhoto',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='GTitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupsharing',
            name='GVideo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
