# Generated by Django 3.2.9 on 2021-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20211211_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsharing',
            name='GMessage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupsharing',
            name='GTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
