# Generated by Django 3.2.9 on 2022-01-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20220117_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Feed_fk',
        ),
    ]
