# Generated by Django 4.1.3 on 2023-01-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20220117_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Userlevel',
            field=models.IntegerField(null=True),
        ),
    ]
