# Generated by Django 4.1.3 on 2023-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_group_userlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Userlevel',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='Userlevel',
            field=models.IntegerField(null=True),
        ),
    ]
