# Generated by Django 4.1.3 on 2023-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_remove_group_userlevel_groupmember_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Userlevel',
            field=models.IntegerField(null=True),
        ),
    ]
