# Generated by Django 4.1.3 on 2023-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_group_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Userlevel',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='Userlevel',
            field=models.IntegerField(default='0'),
        ),
    ]
