# Generated by Django 4.1.3 on 2023-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_alter_group_userlevel_alter_groupmember_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Userlevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='Userlevel',
            field=models.IntegerField(),
        ),
    ]
