# Generated by Django 4.1.3 on 2023-01-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_alter_group_userlevel_alter_groupmember_userlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Userlevel',
        ),
    ]
