# Generated by Django 4.1.3 on 2022-11-22 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=255)),
                ('Pictures', models.ImageField(upload_to='uploads/')),
                ('Video', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'MarketplaceComment',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Message', models.CharField(blank=True, max_length=1500)),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Video', models.FileField(null=True, upload_to='media/')),
                ('Graph', models.FileField(upload_to='videomedia/')),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Message', models.CharField(blank=True, max_length=1500)),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Video', models.FileField(null=True, upload_to='media/')),
                ('Graph', models.FileField(upload_to='videomedia/')),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MarketplaceFeed',
            },
        ),
    ]
