# Generated by Django 4.1.3 on 2022-12-20 07:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=255)),
                ('productDesc', models.CharField(blank=True, max_length=1500)),
                ('productCategory', models.CharField(blank=True, max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('productPhoto', models.ImageField(null=True, upload_to='images/')),
                ('productRating', models.IntegerField(default=0)),
                ('timePosted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prodProduct',
            },
        ),
        migrations.DeleteModel(
            name='MarketplaceComment',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Person_fk',
        ),
        migrations.DeleteModel(
            name='MarketplaceFeed',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
