# Generated by Django 4.1.3 on 2023-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_prodproduct_delete_marketplacecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodproduct',
            name='productStock',
            field=models.IntegerField(default=0),
        ),
    ]
