# Generated by Django 3.2.5 on 2021-11-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
