# Generated by Django 3.2.9 on 2021-11-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='UserLevel',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
