# Generated by Django 3.2.9 on 2021-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_person_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
