# Generated by Django 3.2.9 on 2021-12-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='UserLevel',
            field=models.CharField(max_length=10),
        ),
    ]
