# Generated by Django 4.1.3 on 2022-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
