# Generated by Django 4.1.3 on 2023-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
