# Generated by Django 4.1.3 on 2023-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
