# Generated by Django 4.1.3 on 2023-01-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=1000)),
                ('Address', models.CharField(max_length=1000)),
                ('Payment', models.CharField(max_length=1000)),
                ('NameCard', models.CharField(max_length=1000)),
                ('CreditNumber', models.CharField(max_length=1000)),
                ('Expiration', models.CharField(max_length=1000)),
                ('CVV', models.CharField(max_length=1000)),
                ('transaction_code', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
