# Generated by Django 4.1.3 on 2023-01-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='CVV',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Expiration',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='NameCard',
            new_name='namecard',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
