# Generated by Django 4.1.3 on 2023-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_rename_creditnumber_order_creditnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
