# Generated by Django 3.2.9 on 2021-12-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_booking_programmename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
