# Generated by Django 3.2.9 on 2021-12-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Session',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
