# Generated by Django 3.2.9 on 2021-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20211213_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
