# Generated by Django 3.2.9 on 2022-01-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_person_photo'),
        ('workshop', '0006_auto_20211213_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Person_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
    ]
