# Generated by Django 3.2.9 on 2022-01-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_booking_person_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='Date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
