# Generated by Django 3.2.9 on 2022-01-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20220117_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Name',
        ),
    ]
