# Generated by Django 4.1.5 on 2023-02-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topic.topic')),
            ],
            bases=('topic.topic',),
        ),
        migrations.CreateModel(
            name='RejectTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topic.topic')),
            ],
            bases=('topic.topic',),
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=150)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTopic',
            },
        ),
        migrations.DeleteModel(
            name='ApprovedTopic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='Person_fk',
        ),
        migrations.AddField(
            model_name='topic',
            name='Approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SelectUserTopic',
            fields=[
                ('usertopic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topic.usertopic')),
            ],
            bases=('topic.usertopic',),
        ),
        migrations.DeleteModel(
            name='SuggestedTopic',
        ),
    ]
