# Generated by Django 4.1.5 on 2023-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_approvetopic_rejecttopic_usertopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejecttopic',
            name='topic_ptr',
        ),
        migrations.RemoveField(
            model_name='selectusertopic',
            name='usertopic_ptr',
        ),
        migrations.AddField(
            model_name='usertopic',
            name='Approval',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ApproveTopic',
        ),
        migrations.DeleteModel(
            name='RejectTopic',
        ),
        migrations.DeleteModel(
            name='SelectUserTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
