# Generated by Django 4.1.5 on 2023-02-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_topiccomponent_remove_usertopic_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicComposite',
            fields=[
                ('topiccomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topic.topiccomponent')),
            ],
            bases=('topic.topiccomponent',),
        ),
    ]
