# Generated by Django 3.2.9 on 2022-01-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_person_photo'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Person_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='Graph',
            field=models.FileField(upload_to='videomedia/'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='Message',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='feed',
            name='Video',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
