# Generated by Django 3.2.9 on 2022-01-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_person_photo'),
        ('sharing', '0003_remove_feed_person_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Person_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.person'),
            preserve_default=False,
        ),
    ]
