# Generated by Django 4.1.3 on 2023-01-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basketqty',
            field=models.IntegerField(default=0),
        ),
    ]
