# Generated by Django 4.1.3 on 2023-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basket_basketqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_checkout',
            field=models.BooleanField(default=0),
        ),
    ]
