# Generated by Django 4.1.3 on 2023-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basket_is_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='transaction_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
